
export const enum WS_BASE_EVENT_ID {
    NONE,
    CREATED,
    UPDATED,
    DELETED,
}

export const enum WS_EVENT_ID {
    NONE,
    CLIENT_CREATED,
    CLIENT_UPDATED,
    CLIENT_DELETED,
    FEEDBACK_CREATED,
    FEEDBACK_UPDATED,
    FEEDBACK_DELETED,
}